// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/capacity": {
            "put": {
                "description": "Define la capacidad total para un día y slot.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Admin set capacity",
                "parameters": [
                    {
                        "description": "Set capacity request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.AdminSetCapacityRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/capacity/adjust": {
            "post": {
                "description": "Ajusta capacidad en un rango de fechas (delta puede ser negativo o positivo).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Admin adjust capacity",
                "parameters": [
                    {
                        "description": "Adjust capacity request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.AdminAdjustCapacityRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/capacity/close-days": {
            "post": {
                "description": "Cierra días (total=0) en un rango si no hay reservas activas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Admin close days",
                "parameters": [
                    {
                        "description": "Close days request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.AdminCloseDaysRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/availability": {
            "get": {
                "description": "Consulta la disponibilidad de day slots entre dos fechas para un servicio (por día y slot).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Get availability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "service_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Location ID",
                        "name": "location_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "From date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "To date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.AvailabilityResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/bookings/confirm": {
            "post": {
                "description": "Confirma un booking a partir de un hold y payment_id. Idempotente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Confirm booking",
                "parameters": [
                    {
                        "description": "Confirm booking request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.ConfirmBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ConfirmBookingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Estado de salud simple del servicio.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/holds": {
            "post": {
                "description": "Crea un hold (bloqueo temporal de cupos) para un servicio/fecha/slot.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Create hold",
                "parameters": [
                    {
                        "description": "Create hold request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.CreateHoldRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/httpapi.CreateHoldResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/holds/{id}/cancel": {
            "post": {
                "description": "Cancela un hold. Es idempotente; si el hold no está activo no hace nada.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Cancel hold",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hold ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/internal/holds/expire-now": {
            "post": {
                "description": "Ejecuta el job de expiración de holds de forma inmediata (operación interna).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Expire holds now",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ExpireHoldsNowResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/internal/outbox/pending": {
            "get": {
                "description": "Devuelve mensajes pendientes del outbox (ordenados por created_at).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "List pending outbox",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/booking.OutboxMessage"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "booking.EventType": {
            "type": "string",
            "enum": [
                "HOLD_CREATED",
                "HOLD_CANCELED",
                "HOLD_EXPIRED",
                "BOOKING_CONFIRMED"
            ],
            "x-enum-varnames": [
                "EventHoldCreated",
                "EventHoldCanceled",
                "EventHoldExpired",
                "EventBookingConfirmed"
            ]
        },
        "booking.OutboxMessage": {
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastError": {
                    "type": "string"
                },
                "payload": {
                    "description": "JSON",
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "format": "int32"
                    }
                },
                "sentAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/booking.OutboxStatus"
                },
                "type": {
                    "$ref": "#/definitions/booking.EventType"
                }
            }
        },
        "booking.OutboxStatus": {
            "type": "string",
            "enum": [
                "PENDING",
                "SENT",
                "FAILED"
            ],
            "x-enum-varnames": [
                "OutboxPending",
                "OutboxSent",
                "OutboxFailed"
            ]
        },
        "booking.Slot": {
            "type": "string",
            "enum": [
                "AM",
                "PM"
            ],
            "x-enum-varnames": [
                "SlotAM",
                "SlotPM"
            ]
        },
        "httpapi.AdminAdjustCapacityRequest": {
            "type": "object",
            "properties": {
                "delta": {
                    "type": "integer"
                },
                "from": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "slot": {
                    "description": "AM|PM (si vacío: ambos)",
                    "type": "string"
                },
                "to": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                }
            }
        },
        "httpapi.AdminCloseDaysRequest": {
            "type": "object",
            "properties": {
                "from": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "slot": {
                    "description": "AM|PM (si vacío: ambos)",
                    "type": "string"
                },
                "to": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                }
            }
        },
        "httpapi.AdminSetCapacityRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "slot": {
                    "description": "AM|PM",
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "httpapi.AvailabilityDay": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "slots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.AvailabilityDaySlot"
                    }
                }
            }
        },
        "httpapi.AvailabilityDaySlot": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer"
                },
                "reserved": {
                    "type": "integer"
                },
                "slot": {
                    "description": "AM/PM",
                    "allOf": [
                        {
                            "$ref": "#/definitions/booking.Slot"
                        }
                    ]
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "httpapi.AvailabilityResponse": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.AvailabilityDay"
                    }
                },
                "from": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "to": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                }
            }
        },
        "httpapi.ConfirmBookingRequest": {
            "type": "object",
            "properties": {
                "hold_id": {
                    "type": "string"
                },
                "payment_id": {
                    "type": "string"
                }
            }
        },
        "httpapi.ConfirmBookingResponse": {
            "type": "object",
            "properties": {
                "booking_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "httpapi.CreateHoldRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "description": "YYYY-MM-DD",
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "qty": {
                    "description": "default 1",
                    "type": "integer"
                },
                "service_id": {
                    "type": "string"
                },
                "slot": {
                    "description": "AM|PM",
                    "type": "string"
                }
            }
        },
        "httpapi.CreateHoldResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "RFC3339",
                    "type": "string"
                },
                "hold_id": {
                    "type": "string"
                }
            }
        },
        "httpapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "httpapi.ExpireHoldsNowResponse": {
            "type": "object",
            "properties": {
                "expired": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Paku Booking API",
	Description:      "API del servicio Paku Booking",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
